# mouse stuff
set -g mouse on

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# add a line/space above statusline
set -g pane-border-status bottom
set -g pane-border-format '-'

##### TPM #####
# List of TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "tmux-plugins/tmux-battery"
set -g @plugin "olimorris/tmux-pomodoro-plus"
set -g @plugin "wabri/tmux-nord-plusplus"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
